version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - mvn clean package
      - aws cloudformation package --template-file aws-cloudformation/samTemplate.yaml --s3-bucket copyright-api-build-artifacts --output-template-file outputSamTemplate.yaml
      - aws cloudformation deploy --template-file outputSamTemplate.yaml --capabilities CAPABILITY_IAM --stack-name CopyRightAPI 
artifacts:
  type: 
  files:
    - target/copyright-api-1.0.0-RELEASE.jar
    - samTemplate.yaml
    - outputSamTemplate.yaml