AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CopyRight API - SAM Template

Resources:
  CopyRightApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        ApiKeyRequired: true # sets for all methods

  CopyRightFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: CopyRightHandlerFunction
      Handler: com.deloitte.copyright.lambda.handler.CopyRightLambdaHandler::handleRequest
      Runtime: java11
      CodeUri: target/copyright-api-1.0.0-RELEASE.jar
      Description: 'Lambda function for the Copyright API'
      MemorySize: 1024
      Timeout: 20
      Policies:
        - AWSLambdaExecute
      Events:
        CopyRightApiSam:
          Type: Api
          Properties:
            RestApiId: !Ref CopyRightApi
            Path: /copyright
            Method: post
          Auth:
            ApiKeyRequired: true